language: python
python:
- 3.7
- 3.6
- 3.5
- 2.7
matrix:
  include:
  - name: Python on Xenial Linux
    dist: xenial
  - name: Python on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
  - name: Python on Windows
    os: windows
    language: shell
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    before_install:
      - choco install python
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: aiguofer
  password:
    secure: hAyppEoL6R57np2Me36Mua966Ju/15D3Xu/g3FLy24kK+2nD9x7pWLblhuEyX9lYwNwYoRwYJpi8/epXIVu/JwbfTksl6L0M84FECtiwnQyOCHjSJCLWJcZyE6aqJD8bvFU2HIee1+JMK97DFg1HZa/yi2Lv61xvxzFq/QxXdUh7clLemZsb/uc7QENIRDKwwqUraj0AlUAFbhtG4HDGiyStRmI+V4f0nmCdG98aSbwiveQAFMClIIW1JdvGmKOoVtRG84dwHYb8ExwmazQlgcHLJiB7IXPd+zIu/67EufPS5424MdhY07D83uayLidU1cT9vJHHd+1Os2VjeyzQwSUmLF1Whc2xFCp4eu3Sw619x4kheI5AH5F1xEzi9S0XVDhTuH2D39A5Lpg06YIbRd2B61z3unZVYJqGYV4UQV3hHcNBPKN8Ka6VsDOSl7qSbDOWwwfLBszbC24yoABOrg3pBO0FMVHMtx1CA15D36ZAVxIV45TP2TyXCezkjvUmUgop4oQJ7qA7Kkd9LSr13gBwvH2PLvXUzMU3RUGF/Dgqbyz9GBiKVS7OgJYNQH1lnuOPLMj6I5jBD+2uTlxXedgOgxzUBU926YiZ5pqiwuQvpkLguBLvZseCl4kKTWmeNQSZoNCWhy8afrcfdFpg+hiN5fyTe4BUGFW4Kivcb7E=
  on:
    tags: true
    repo: aiguofer/gspread-pandas
    python: '3.6'
